e_shell/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('', include('store.urls')),
    path('', include('staff.urls')),
]
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)

staff/urls.py
from django.urls import path
from .views import *
from authentication.views import staff_login, staff_logout

urlpatterns = [
    path('staff/', products_list, name='staff_index'),

    path('products/', products_list, name='products_list'),
    path('add_product/', add_product, name='add_product'),
    path('edit_product/<int:pk>/', ProductUpdateView.as_view(), name='edit_product'),
    path('delete_product/<int:id>', delete_product, name='delete_product'),

    path('products-category/', product_category, name='Product_category'),
    path('add_category/', add_category, name='add_category'),
    path('edit_category/<int:pk>/', CategoryUpdateView.as_view(), name='edit_category'),
    path('delete_category/<int:id>', delete_category, name='delete_category'),

    path('products-sub-category/', product_sub_category, name='Product_sub_category'),
    path('add_sub_category/', add_sub_category, name='add_sub_category'),
    path('edit_sub_category/<int:pk>/', SubCategoryUpdateView.as_view(), name='edit_sub_category'),
    path('delete_sub_category/<int:id>', delete_sub_category, name='delete_sub_category'),

    path('products-sub-sub-category/', Product_sub_sub_category, name='Product_sub_sub_category'),
    path('add_sub_sub_category/', add_sub_sub_category, name='add_sub_sub_category'),
	path('edit_sub_sub_category/<int:pk>/', SubSubCategoryUpdateView.as_view(), name='edit_sub_sub_category'),
	path('delete_sub_sub_category/<int:id>', delete_sub_sub_category, name='delete_sub_sub_category'),


    path('login/', staff_login, name='login'),
    path('logout/', staff_logout, name='logout')
]

store/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('update_item/', views.updateItem, name="update_item"),
    path('', views.Home.as_view(), name="home"),
    path('product/', views.ShopProduct.as_view(), name="product"),
    path('product_details/<int:pk>/', views.ProductDetails.as_view(), name="product_details"),
    path('add_to_cart/<int:pk>/', views.add_to_cart, name="add_to_cart"),
    path('cart/', views.CartItems.as_view(), name="cart"),
    path('remove_from_cart/<int:pk>/', views.remove_from_cart, name="remove_from_cart"),
    path('remove_single_item_from_cart/<int:pk>/', views.remove_single_item_from_cart,
         name="remove_single_item_from_cart"),
    path('remove_from_cart/<int:pk>/', views.remove_from_cart, name="remove_from_cart"),
    path('checkout/', views.CheckOut.as_view(), name="checkout"),
    # Delivery
    path('add_delivery_info/', views.AddDeliveryInfo.as_view(), name="add_delivery_info"),
    path('sub_categories/<int:pk>/', views.SubCategoriesDateils.as_view(), name="sub_categories"),
    path('sub_sub_categories/<int:pk>/', views.SubSubCategoriesDateils.as_view(), name="sub_sub_categories"),
    path('search/', views.search_product, name="search"),
    path('edit_product/<int:pk>', views.edit_product, name="edit_product"),

]

store/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.datetime_safe import datetime
from django_countries.fields import CountryField
from e_shell import settings


class Category(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=200, null=True)
    create_on = models.DateTimeField(default=timezone.now)

    def get_absolute_url(self):
        return reverse('Product_category')

    class Meta:
        verbose_name_plural = 'Product Category'

    def __str__(self):
        return self.name


class SubCategory(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=200, null=True)
    create_on = models.DateTimeField(default=datetime.now)

    def get_absolute_url(self):
        return reverse('Product_sub_category')

    class Meta:
        verbose_name_plural = 'Product Sub Category'

    def __str__(self):
        return f'{self.name} from {self.category}'


class SubSubCategory(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=200, null=True)
    create_on = models.DateTimeField(default=datetime.now)

    class Meta:
        verbose_name_plural = 'Product Sub sub Category'

    def get_absolute_url(self):
        return reverse('Product_sub_sub_category')

    def __str__(self):
        return f'{self.name}from {self.subcategory}'


class Product(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    sub_category = models.ForeignKey(SubSubCategory, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=200, null=True)
    price = models.CharField(max_length=12, null = True)
    discount = models.CharField(max_length=200, null=True, blank=True)
    digital = models.BooleanField(default=False, null=True, blank=False)
    image = models.ImageField(upload_to='product_image', null=True, blank=True)
    available = models.CharField(max_length=30, null=True, blank=True)
    label = models.CharField(max_length=30, null=True)
    description = models.TextField(max_length=500, null=True)

    class Meta:
        verbose_name_plural = 'Product'

    def __str__(self):
        return self.name


    def get_absolute_url(self):
        return reverse('products_list')

    @property
    def get_add_to_cart_url(self):
        return reverse('add_to_cart', kwargs={
            'pk': self.pk
        })

    def get_remove_from_cart_url(self):
        return reverse('remove_from_cart', kwargs={
            'pk': self.pk
        })

    def get_remove_single_item_from_cart(self):
        return reverse('remove_single_item_from_cart', kwargs={'pk': self.pk})

    def get_individual_product_VAT(self):
        VAT = float(self.price) * float(18/100)

        return VAT



class OrderItem(models.Model):
    customer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, blank=True, null=True)
    ordered = models.BooleanField(default=False, null=True)
    quantity = models.IntegerField(default=1, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)
    session_key = models.CharField(max_length=40, null=True)

    # class Meta:
    #     verbose_name_plural = 'Ordered products'
    #
    def get_product_id(self):
        try:
            product_id = self.product.id
        except:
            return None
        return product_id

    @property
    def get_individual_product_name(self):
        try:
            product_name = self.product.name
        except:
            return None

        return product_name

    @property
    def get_individual_product_image(self):
        try:
            image = self.product.image.url
        except:
            return None

        return image

    @property
    def get_individual_product_price(self):
        try:
            price = self.product.price
        except:
            return None
        return price

    @property
    def get_add_to_cart(self):
        try:
            add_to_cart = self.product.get_add_to_cart_url()
        except:
            return None

        return add_to_cart

    @property
    def get_total(self):
        try:
            total = self.product.price * self.quantity
        except:
            return None
        return total

    def __str__(self):
        return f'{self.product} Quantity of {self.quantity}'


    def get_toatal_VAT(self):

        try:
            totalVAT = self.product.get_individual_product_VAT() * self.quantity
        except:
            return 0
        return totalVAT


class Order(models.Model):
    ref_id = models.CharField(max_length=40, null=True)
    customer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True,
                                 related_name='order')
    date_ordered = models.DateTimeField(auto_now_add=True)
    order_items = models.ManyToManyField(OrderItem)
    ordered = models.BooleanField(default=False, null=True)
    deliveryInfo = models.ForeignKey('OrderDeliveryInfo', on_delete=models.CASCADE, null=True)
    shippingAddress = models.ForeignKey('ShippingAddress', on_delete=models.CASCADE, null=True)
    transaction_id = models.CharField(max_length=200, null=True)
    session_key = models.CharField(max_length=40, null=True)

    class Meta:
        verbose_name_plural = 'Orders'

    def __str__(self):
        if self.customer is not None:
            return str(self.customer)
        else:
            return f'no user'

    @property
    def shipping(self):
        shipping = False
        orderitems = self.order_items.all()
        for i in orderitems:
            if not i.product.digital:
                shipping = True
        return shipping

    # Getting the total value of the cart
    @property
    def get_cart_total(self):
        try:
            orderitems = self.order_items.all()
            total = sum([item.get_total for item in orderitems])
        except:
            return None
        return total

    @property
    def get_total_product_vat(self):

        total_vat =0
        try:
            for item in self.order_items.all():
                total_vat += item.get_toatal_VAT()
        except:
            return 0
        return total_vat





    # Getting the total value of the item
    @property
    def get_cart_items_total(self):
        total_items = 0
        orderitems = self.order_items.all()
        total = sum([item.quantity for item in orderitems])
        return total


class OrderDeliveryInfo(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    pickup_order_at_station = models.CharField(max_length=200, null=True)
    deliver_my_order = models.CharField(max_length=200, null=True)
    insure_my_order = models.CharField(max_length=200, null=True)
    same_day_delivery = models.CharField(max_length=200, null=True)
    express_delivery = models.CharField(max_length=200, null=True)

    def __str__(self):
        return 'Delivery info'


class ShippingAddress(models.Model):
    customer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True)
    # order must have shipping address and not viscera
    # order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    address1 = models.CharField(max_length=200, null=True)
    address2 = models.CharField(max_length=200, null=True)
    city = models.CharField(max_length=200, null=True)
    region = models.CharField(max_length=200, null=True)
    date_added = models.DateTimeField(auto_now_add=True)
    phone = models.CharField(max_length=20, null=True)
    tin_number = models.CharField(max_length=10, null=True)
    country = CountryField(null=True)
    # added field
    description = models.CharField(max_length=200, null=True)
    payment_option = models.CharField(max_length=20, null=True)

    class Meta:
        verbose_name_plural = 'Shipping address'

    def __str__(self):
        return str(self.customer)

store/forms.py
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget


class CheckoutForm(forms.Form):
    address1 = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'address(Town)'
    }))
    address2 = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'address2'
    }))
    city = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'city'
    }))
    region = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Region'
    }))

    phone = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'phone number'

    }))
    tin_number = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'TIN number'
    }))
    # added field
    description = forms.CharField(widget=forms.Textarea(attrs={

        'cols': 23,
        'rows': 1,
        'placeholder': 'Description'
    }))
    country = CountryField(blank_label='(select country)').formfield(
        required=False,
        widget=CountrySelectWidget(attrs={
            'class': 'custom-select d-block w-100',
        }))
    pay_option = forms.CharField()


class EditProductForm(forms.Form):
    quantity = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'value': '3',
    }))


class GuestUserForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control'}
    ))
    email = forms.CharField(widget=forms.EmailInput(
        attrs={'class': 'form-control'}
    ))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control'
        }
    ))

templates/store/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section id="cart_items" xmlns="http://www.w3.org/1999/html">
		<div class="container">

			<div class="table-responsive cart_info">
				<table class="table table-condensed">
					<thead>
						<tr class="cart_menu">
							<td class="image">Item</td>
							<td class="description"></td>
							<td class="price">Price</td>
							<td class="quantity">Quantity</td>
							<td class="total">Total</td>
							<td></td>
						</tr>
					</thead>
					<tbody>
                    {% for cart_item in order_items %}
						<tr>
							<td class="cart_product">
								<a  href=""><img style="width:50px; height:50px;" src="{{cart_item.product.image.url}}" alt=""></a>
							</td>
							<td class="cart_description">
								<h4><a href="">{{cart_item.product.name|truncatechars:20}}</a></h4>
								<p>Web ID: 1089772</p>
							</td>
							<td class="cart_price">
								<p>Tshs {{cart_item.product.price}}</p>
							</td>
							<td class="cart_quantity">
								<div class="cart_quantity_button">
									<a class="cart_quantity_up" href="{{cart_item.product.get_add_to_cart_url}}"> + </a>

                                        <input class="cart_quantity_input" type="text" name="quantity" value="{{cart_item.quantity}}" autocomplete="off" size="2">

                                    <a class="cart_quantity_down" href="{{cart_item.product.get_remove_single_item_from_cart}}"> - </a>
								</div>
							</td>
							<td class="cart_total">
								<p class="cart_total_price">Tshs {{cart_item.get_total}}</p>
							</td>
							<td class="cart_delete">
								<a class="cart_quantity_delete" href="{{cart_item.product.get_remove_from_cart_url}}"><i class="fa fa-times"></i></a>
							</td>
						</tr>
                    {% endfor %}

					</tbody>
				</table>
			</div>
		</div>
	</section> <!--/#cart_items-->

	<section id="do_action">
		<div class="container">
			<div class="heading">
				<h3>What would you like to do next?</h3>
				<p>Choose if you would like to pickup your order yourself or have it delivered as well as have it insurance</p>
			</div>
			<div class="row">
				<form action="{% url 'add_delivery_info'  %}" method="post">
					{% csrf_token%}
				<div class="col-sm-4">
					<div class="chose_area">

						<ul class="user_option">
							<li>
								<input type="checkbox" name="pickup_order_at_station" value="Pickup order at Station">
								<label>Pickup order at Station</label>
							</li>
							<li>
								<input type="checkbox"name="deliver_my_order" value="Deliver my order">
								<label>Deliver my order</label>
							</li>
							<li>
								<input type="checkbox" name="insure_my_order" value="Insurance my order">
								<label>Insurance my order</label>
							</li>
						</ul>


					</div>
				</div>
				<div class="col-sm-4">
					<div class="chose_area">
						<ul class="user_option">
							<li>
								<input type="checkbox" name="same_day_delivery" value="Same day delivery">
								<label>Same day delivery</label>
							</li>
							<li>
								<input type="checkbox" name="express_delivery" value="Express delivery">
								<label>Express delivery</label>
							</li>
							<li>
								<input type="checkbox" name="standard_delivery" value="Standard delivery">
								<label>Standard delivery</label>
							</li>
						</ul>

					</div>
				</div>
				<div class="col-sm-4">
					<div class="total_area">
						<ul>
							<li>Cart Items <span>{{order.get_cart_items}}</span></li>
							<li>Cart Sub Total <span>Tshs {{order.get_cart_total|floatformat:2}}</span></li>
							<li>Vat <span>Tshs {{order.get_total_product_vat}}</span></li>
							<li>Shipping Cost <span>Free</span></li>
							<li>Total <span>Tshs {{order.get_cart_total|floatformat:2}}</span></li>
						</ul>
							<button type="submit" class="btn btn-default check_out" >Check Out</button>
					</div>
				</div>
			</form>
			</div>
		</div>
	</section><!--/#do_action-->

{% endblock content %}

templates/store/product_details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
	<section>
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<div class="left-sidebar">
						<h2>Category</h2>
						<div class="panel-group category-products" id="accordian"><!--category-productsr-->
							{% for category in categories %}
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title">
										<a data-toggle="collapse" data-parent="#accordian" href="#{{category.id}}">
											<span class="badge pull-right"><i class="fa fa-plus"></i></span>
											{{category.name}}
										</a>
									</h4>
								</div>
								<div id="{{category.id}}" class="panel-collapse collapse">
									<div class="panel-body">
										<ul>
											{% for sub_categories in category.subcategory_set.all %}
											<li>
												<a href="{% url 'sub_categories' sub_categories.id %}" >{{sub_categories.name}}</a>

                                             </li>
											{%empty%}
											<div class="alert alert-info" role="alert">
  												No sub categories for now
											</div>
											{% endfor %}

										</ul>
									</div>
								</div>
							</div>
							{%endfor%}
						</div><!--/category-products-->


					</div>
				</div>

				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="{{object.image.url}}" alt="" />
							</div>
							<div id="similar-product" class="carousel slide" data-ride="carousel">

								  <!-- Wrapper for slides -->
								    <div class="carousel-inner">
										<div class="item active">
										  <a href=""><img src="images/product-details/similar1.jpg" alt=""></a>
										  <a href=""><img src="images/product-details/similar2.jpg" alt=""></a>
										  <a href=""><img src="images/product-details/similar3.jpg" alt=""></a>
										</div>
										<div class="item">
										  <a href=""><img src="images/product-details/similar1.jpg" alt=""></a>
										  <a href=""><img src="images/product-details/similar2.jpg" alt=""></a>
										  <a href=""><img src="images/product-details/similar3.jpg" alt=""></a>
										</div>
										<div class="item">
										  <a href=""><img src="images/product-details/similar1.jpg" alt=""></a>
										  <a href=""><img src="images/product-details/similar2.jpg" alt=""></a>
										  <a href=""><img src="images/product-details/similar3.jpg" alt=""></a>
										</div>

									</div>
							</div>

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<img src="" class="newarrival" alt="" />
								<h2>{{object.name}}</h2>
								<p>Total: {{object.get_total}}</p>
								<img src="" alt="" />
								<form id="edit_product" method="post">
									{% csrf_token %}
								<span>
									{% if object.discount%}
									<span>Tshs {{object.discount}}</span>
									<span style="color:gray;"><small><s>Tshs {{object.price}}</s><small></span>
									{% else %}
									<span>Tshs {{object.price}}</span>
									{%endif%}
<!--									<label for="id_quantity">Quantity</label>-->
<!--									<input type="text" name="quantity"   value="3" required="" id="id_quantity">-->
<!--									<button type="submit" style="border-color:red;" class="btn btn-inline-primary">Edit product</button>-->
								</span>
								</form>
								<p><b>Availability:</b> {{object.available}} In Stock</p>
								<p><b>Condition:</b> {{object.label}}</p>
								<p><b>Brand:</b> {{object.sub_category}}</p>
								<p><b>Description:</b>{{object.description}}</p>
								<a href=""><img src="" class="share img-responsive"  alt="" /></a>
								<a href="{{object.get_add_to_cart_url}}" class="btn btn-default cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
								</a>

							</div><!--/product-information-->
						</div>
					</div><!--/product-details-->


					<div class="recommended_items"><!--recommended_items-->
						<h2 class="title text-center">recommended items</h2>

						<div id="recommended-item-carousel" class="carousel slide" data-ride="carousel">
							<div class="carousel-inner">
								{% for recommend in recommend %}
								<div class="item active">
									<div class="col-sm-4">
										<div class="product-image-wrapper">
											<div class="single-products">
												<div class="productinfo text-center">
													<img style=" height:200px; width:200px;" src="{{recommend.get_individual_product_image}}" alt="" />
													<h2>{{recommend.get_individual_product_price}}</h2>
													<p></p>
													<a href="{{recommend.get_add_to_cart}}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
												</div>

											</div>
										</div>
									</div>

								</div>
								{%endfor%}



							</div>
							 <a class="left recommended-item-control" href="#recommended-item-carousel" data-slide="prev">
								<i class="fa fa-angle-left"></i>
							  </a>
							  <a class="right recommended-item-control" href="#recommended-item-carousel" data-slide="next">
								<i class="fa fa-angle-right"></i>
							  </a>
						</div>
					</div><!--/recommended_items-->

				</div>
			</div>
		</div>
	</section>
{% block javascript %}
<script>
	$("#edit_product").submit(function(e){
	    e.preventDefault();
        const serializedData = $(this).serialize();
        $.ajax({
            type:'POST',
            url:"{% url 'edit_product' object.id %}",
            data:serializedData,
            success: function (response){
                $('#edit_product').trigger('reset');
                 alert(response["responseJSON"]["message"]);
            },

            error: function (response) {
                // alert the error if any error occured
                alert(response["responseJSON"]["error"]);
            }
        })
    })
</script>

{% endblock javascript %}


{% endblock content %}

templates/store/search.html
<form action="{% url 'search' %}" method="GET" value="{{request.GET.q}}">
    <div class="row">
        <div class="col-sm-9">
              <input class="form-control" type="text" name="q" value="{{request.GET.q}}" placeholder="Search posts"/>
        </div>
        <div class="col-sm-3">
            <input style="display:inline; background-color:#f5b342;" type="submit" class="btn btn-inline-danger" name="submit" value="Search"/>
        </div>
    </div>
</form>

templates/store/sub_categories_details.html
{% extends 'base.html' %}
{% load static %}
{% block content%}

<section id="slider"><!--slider-->
		<div class="container" style="width:88%; ">
			<div class="row">
				<div class="col-sm-12">
					<div id="slider-carousel" class="carousel slide" data-ride="carousel">
						<ol class="carousel-indicators">
							<li data-target="#slider-carousel" data-slide-to="0" class="active"></li>
							<li data-target="#slider-carousel" data-slide-to="1"></li>
							<li data-target="#slider-carousel" data-slide-to="2"></li>
						</ol>
<!---->
						<div class="carousel-inner">
							<div class="item active">
								<div class="col-sm-6">

									<h1><span>Vel-</span>Lubricant</h1>
									<h2>Best quality Lubricants</h2>
									<p>Shop hustle free with our great prices</p>
									<button type="button" class="btn btn-default get">Get it now</button>
								</div>
								<div class="col-sm-6">
									<img src="{% static 'images/total/gear8.png' %}" class="girl img-responsive" alt="" />
									<img src="{% static 'images/home/pricing.png' %}"  class="pricing" alt="" />
								</div>
							</div>
							<div class="item">
								<div class="col-sm-6">

									<h1><span>Vel-</span>Lubricant</h1>
									<h2>Best quality Lubricants</h2>
									<p>Shop hustle free with our great prices</p>
									<button type="button" class="btn btn-default get">Get it now</button>
								</div>
								<div class="col-sm-6">
									<img  src="{% static 'images/total/gear8.png' %}" class="girl img-responsive" alt="" />
									<img src="{% static 'images/home/pricing.png'%}"  class="pricing" alt="" />
								</div>
							</div>

							<div class="item">
								<div class="col-sm-6">

									<h1><span>Vel-</span>Lubricant</h1>
									<h2>Best quality Lubricants</h2>
									<p>Shop hustle free with our great prices</p>
									<button type="button" class="btn btn-default get">Get it now</button>
								</div>
								<div class="col-sm-6">
									<img src="{% static 'images/total/gear8.png'%}" class="girl img-responsive" alt="" />
									<img src="{% static 'images/home/pricing.png" class="pricing" alt="" />
								</div>
							</div>

						</div>

						<a href="#slider-carousel" class="left control-carousel hidden-xs" data-slide="prev">
							<i class="fa fa-angle-left"></i>
						</a>
						<a href="#slider-carousel" class="right control-carousel hidden-xs" data-slide="next">
							<i class="fa fa-angle-right"></i>
						</a>
					</div>

				</div>
			</div>
		</div>
	</section><!--/slider-->

<section>
		<div class="container" style="width:88%;">
			<div class="row">
				<div class="col-sm-3">
					<div class="left-sidebar">
						<h2>{{object.name}}</h2>

						<div class="panel-group category-products" id="accordian"><!--category-productsr-->
							{% for subsubcategory in object.subsubcategory_set.all%}
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title">
										<a  href="{% url 'sub_sub_categories' subsubcategory.id %}">
											<span class="badge pull-right"><i class="fa fa-plus"></i></span>
											{{subsubcategory.name}}
										</a>
									</h4>
								</div>

							</div>
							{% endfor %}

						</div><!--/category-products-->



					</div>
				</div>

				<div class="col-sm-9 padding-right">
					<div class="features_items"><!--features_items-->
						<h2 class="title text-center">{{object.name}}</h2>

						{% for product in object.subsubcategory_set.all %}
							{% for sub in product.product_set.all %}

							<div style="margin-right:-20px;" class="col-sm-4">
								<div style="" class="product-image-wrapper">
									<div class="single-products">
											<div class="productinfo text-center">
												<img style="width:150px; height:200px;" src="{{sub.image.url}}" alt="" />
												<h2>Tshs {{sub.price}}</h2>
												<p>{{sub.name}}</p>
												<p>{{sub.sub_category}}</p>
												<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
											</div>
											<div style="background-color:hsla(50, 33%, 25%, 0.85);" class="product-overlay">
												<div class="overlay-content">
													<h2>TSH: {{sub.price}}</h2>
													<p>{{sub.name}}</p>
													<p>{{sub.sub_category}}</p>
													<a href="{{sub.get_add_to_cart_url}}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
													<a href="{% url 'product_details' product.pk %}" class="btn btn-default add-to-cart">Read more</a>
												</div>
											</div>
									</div>
								</div>
							</div>

							{% endfor %}
						{% endfor %}


					</div><!--features_items-->


					<div class="recommended_items"><!--recommended_items-->
						<h2 class="title text-center">recommended items</h2>

						<div id="recommended-item-carousel" class="carousel slide" data-ride="carousel">
							<div class="carousel-inner">
								{% for recommend in recommend %}
								<div class="item active">
									<div class="col-sm-4">
										<div class="product-image-wrapper">
											<div class="single-products">
												<div class="productinfo text-center">
													<img style=" height:200px; width:200px;" src="{{recommend.get_individual_product_image}}" alt="" />
													<h2>{{recommend.get_individual_product_price}}</h2>
													<p></p>
													<a href="{{recommend.get_add_to_cart}}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
												</div>

											</div>
										</div>
									</div>

								</div>
								{%endfor%}

							</div>
							 <a class="left recommended-item-control" href="#recommended-item-carousel" data-slide="prev">
								<i class="fa fa-angle-left"></i>
							  </a>
							  <a class="right recommended-item-control" href="#recommended-item-carousel" data-slide="next">
								<i class="fa fa-angle-right"></i>
							  </a>
						</div>
					</div><!--/recommended_items-->

				</div>
			</div>
		</div>
	</section>
{% endblock content%}